-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE, PRODUCT.PRICE * SUM(OFFLINE_SALE.SALES_AMOUNT) AS SALES
FROM PRODUCT INNER JOIN OFFLINE_SALE
WHERE PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;

# SELECT *
# FROM PRODUCT INNER JOIN OFFLINE_SALE
# WHERE PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
# # GROUP BY PRODUCT_CODE

# SELECT PRODUCT_CODE, SUM(SALES_AMOUNT) 
# FROM PRODUCT INNER JOIN OFFLINE_SALE
# WHERE PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
# GROUP BY PRODUCT_CODE

# 2	C1000000	51000	1	2	1	2022-01-01 00:00:00