SELECT F.ID AS ID, FN.FISH_NAME AS FISH_NAME, MAX_FISH.MAX_LENGTH AS LENGTH
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS FN ON F.FISH_TYPE = FN.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    ) AS MAX_FISH
ON F.FISH_TYPE = MAX_FISH.FISH_TYPE AND F.LENGTH = MAX_FISH.MAX_LENGTH
ORDER BY ID;